/* eslint-disable */
/**
 * AUTO-GENERATED by scripts/generate-icon-registry.mjs
 * Do not edit. Run: npm run icons:generate
 * Icons: 319
 */

import type { FC } from 'react';
import type { SvgProps } from 'react-native-svg';

import Icon_city_icons_generic_arrow_narrow_right from '@/city-icons/generic/arrow-narrow-right.svg';
import Icon_city_icons_generic_bolt from '@/city-icons/generic/bolt.svg';
import Icon_city_icons_generic_building_castle from '@/city-icons/generic/building-castle.svg';
import Icon_city_icons_generic_droplet from '@/city-icons/generic/droplet.svg';
import Icon_city_icons_generic_handcuffs from '@/city-icons/generic/handcuffs.svg';
import Icon_city_icons_generic_parking from '@/city-icons/generic/parking.svg';
import Icon_city_icons_generic_plane_tilt from '@/city-icons/generic/plane-tilt.svg';
import Icon_city_icons_generic_prison from '@/city-icons/generic/prison.svg';
import Icon_city_icons_generic_question_mark from '@/city-icons/generic/question-mark.svg';
import Icon_city_icons_generic_receipt_tax from '@/city-icons/generic/receipt-tax.svg';
import Icon_city_icons_generic_tax from '@/city-icons/generic/tax.svg';
import Icon_city_icons_generic_treasure_chest from '@/city-icons/generic/treasure-chest.svg';
import Icon_city_icons_icons_ad_andorra from '@/city-icons/icons/ad-andorra.svg';
import Icon_city_icons_icons_ae_abu_dhabi from '@/city-icons/icons/ae-abu-dhabi.svg';
import Icon_city_icons_icons_ae_dubai from '@/city-icons/icons/ae-dubai.svg';
import Icon_city_icons_icons_ag_saint_john from '@/city-icons/icons/ag-saint-john.svg';
import Icon_city_icons_icons_al_tirana from '@/city-icons/icons/al-tirana.svg';
import Icon_city_icons_icons_am_yerevan from '@/city-icons/icons/am-yerevan.svg';
import Icon_city_icons_icons_ar_buenos_aires from '@/city-icons/icons/ar-buenos-aires.svg';
import Icon_city_icons_icons_ar_cordoba from '@/city-icons/icons/ar-cordoba.svg';
import Icon_city_icons_icons_ar_ushuaia from '@/city-icons/icons/ar-ushuaia.svg';
import Icon_city_icons_icons_at_graz from '@/city-icons/icons/at-graz.svg';
import Icon_city_icons_icons_at_hallstatt from '@/city-icons/icons/at-hallstatt.svg';
import Icon_city_icons_icons_at_vienna from '@/city-icons/icons/at-vienna.svg';
import Icon_city_icons_icons_au_canberra from '@/city-icons/icons/au-canberra.svg';
import Icon_city_icons_icons_au_hobart from '@/city-icons/icons/au-hobart.svg';
import Icon_city_icons_icons_au_melbourne from '@/city-icons/icons/au-melbourne.svg';
import Icon_city_icons_icons_au_perth from '@/city-icons/icons/au-perth.svg';
import Icon_city_icons_icons_au_sydney from '@/city-icons/icons/au-sydney.svg';
import Icon_city_icons_icons_az_baku from '@/city-icons/icons/az-baku.svg';
import Icon_city_icons_icons_ba_mostar from '@/city-icons/icons/ba-mostar.svg';
import Icon_city_icons_icons_ba_sarajevo from '@/city-icons/icons/ba-sarajevo.svg';
import Icon_city_icons_icons_bd_dhaka from '@/city-icons/icons/bd-dhaka.svg';
import Icon_city_icons_icons_be_bruges from '@/city-icons/icons/be-bruges.svg';
import Icon_city_icons_icons_be_brussels from '@/city-icons/icons/be-brussels.svg';
import Icon_city_icons_icons_bf_ouagadougou from '@/city-icons/icons/bf-ouagadougou.svg';
import Icon_city_icons_icons_bg_burgas from '@/city-icons/icons/bg-burgas.svg';
import Icon_city_icons_icons_bg_sofia from '@/city-icons/icons/bg-sofia.svg';
import Icon_city_icons_icons_bh_manama from '@/city-icons/icons/bh-manama.svg';
import Icon_city_icons_icons_bn_seria from '@/city-icons/icons/bn-seria.svg';
import Icon_city_icons_icons_bo_la_paz from '@/city-icons/icons/bo-la-paz.svg';
import Icon_city_icons_icons_br_brasilia from '@/city-icons/icons/br-brasilia.svg';
import Icon_city_icons_icons_br_rio_de_janeiro from '@/city-icons/icons/br-rio-de-janeiro.svg';
import Icon_city_icons_icons_br_sao_paulo_masp from '@/city-icons/icons/br-sao-paulo-masp.svg';
import Icon_city_icons_icons_br_sao_paulo from '@/city-icons/icons/br-sao-paulo.svg';
import Icon_city_icons_icons_bs_nassau from '@/city-icons/icons/bs-nassau.svg';
import Icon_city_icons_icons_bt_thimphu from '@/city-icons/icons/bt-thimphu.svg';
import Icon_city_icons_icons_by_minsk from '@/city-icons/icons/by-minsk.svg';
import Icon_city_icons_icons_bz_san_ignacio from '@/city-icons/icons/bz-san-ignacio.svg';
import Icon_city_icons_icons_ca_ottawa from '@/city-icons/icons/ca-ottawa.svg';
import Icon_city_icons_icons_ca_toronto from '@/city-icons/icons/ca-toronto.svg';
import Icon_city_icons_icons_ca_vancouver from '@/city-icons/icons/ca-vancouver.svg';
import Icon_city_icons_icons_ch_bern from '@/city-icons/icons/ch-bern.svg';
import Icon_city_icons_icons_ci_yamoussoukro from '@/city-icons/icons/ci-yamoussoukro.svg';
import Icon_city_icons_icons_cl_santiago from '@/city-icons/icons/cl-santiago.svg';
import Icon_city_icons_icons_cl_valparaiso from '@/city-icons/icons/cl-valparaiso.svg';
import Icon_city_icons_icons_cn_beijing from '@/city-icons/icons/cn-beijing.svg';
import Icon_city_icons_icons_cn_chengdu from '@/city-icons/icons/cn-chengdu.svg';
import Icon_city_icons_icons_cn_jingzhou from '@/city-icons/icons/cn-jingzhou.svg';
import Icon_city_icons_icons_cn_leshan from '@/city-icons/icons/cn-leshan.svg';
import Icon_city_icons_icons_cn_shanghai from '@/city-icons/icons/cn-shanghai.svg';
import Icon_city_icons_icons_co_bogota from '@/city-icons/icons/co-bogota.svg';
import Icon_city_icons_icons_co_cartagena from '@/city-icons/icons/co-cartagena.svg';
import Icon_city_icons_icons_co_medellin from '@/city-icons/icons/co-medellin.svg';
import Icon_city_icons_icons_cr_alajuela from '@/city-icons/icons/cr-alajuela.svg';
import Icon_city_icons_icons_cu_havana from '@/city-icons/icons/cu-havana.svg';
import Icon_city_icons_icons_cw_willemstadt from '@/city-icons/icons/cw-willemstadt.svg';
import Icon_city_icons_icons_cy_limassol from '@/city-icons/icons/cy-limassol.svg';
import Icon_city_icons_icons_cy_nicosia from '@/city-icons/icons/cy-nicosia.svg';
import Icon_city_icons_icons_cy_paphos from '@/city-icons/icons/cy-paphos.svg';
import Icon_city_icons_icons_cz_prague from '@/city-icons/icons/cz-prague.svg';
import Icon_city_icons_icons_de_aachen from '@/city-icons/icons/de-aachen.svg';
import Icon_city_icons_icons_de_berlin from '@/city-icons/icons/de-berlin.svg';
import Icon_city_icons_icons_de_bielefeld from '@/city-icons/icons/de-bielefeld.svg';
import Icon_city_icons_icons_de_bremen from '@/city-icons/icons/de-bremen.svg';
import Icon_city_icons_icons_de_cologne from '@/city-icons/icons/de-cologne.svg';
import Icon_city_icons_icons_de_erfurt from '@/city-icons/icons/de-erfurt.svg';
import Icon_city_icons_icons_de_frankfurt from '@/city-icons/icons/de-frankfurt.svg';
import Icon_city_icons_icons_de_freiburg from '@/city-icons/icons/de-freiburg.svg';
import Icon_city_icons_icons_de_giessen from '@/city-icons/icons/de-giessen.svg';
import Icon_city_icons_icons_de_hamburg from '@/city-icons/icons/de-hamburg.svg';
import Icon_city_icons_icons_de_karlsruhe from '@/city-icons/icons/de-karlsruhe.svg';
import Icon_city_icons_icons_de_leipzig from '@/city-icons/icons/de-leipzig.svg';
import Icon_city_icons_icons_de_leverkusen from '@/city-icons/icons/de-leverkusen.svg';
import Icon_city_icons_icons_de_munich from '@/city-icons/icons/de-munich.svg';
import Icon_city_icons_icons_de_nuremberg from '@/city-icons/icons/de-nuremberg.svg';
import Icon_city_icons_icons_de_siegen from '@/city-icons/icons/de-siegen.svg';
import Icon_city_icons_icons_de_stuttgart from '@/city-icons/icons/de-stuttgart.svg';
import Icon_city_icons_icons_dk_copenhagen from '@/city-icons/icons/dk-copenhagen.svg';
import Icon_city_icons_icons_ec_quito from '@/city-icons/icons/ec-quito.svg';
import Icon_city_icons_icons_ee_tallinn from '@/city-icons/icons/ee-tallinn.svg';
import Icon_city_icons_icons_eg_cairo from '@/city-icons/icons/eg-cairo.svg';
import Icon_city_icons_icons_er_asmara from '@/city-icons/icons/er-asmara.svg';
import Icon_city_icons_icons_es_barcelona from '@/city-icons/icons/es-barcelona.svg';
import Icon_city_icons_icons_es_cordoba from '@/city-icons/icons/es-cordoba.svg';
import Icon_city_icons_icons_es_coruna from '@/city-icons/icons/es-coruna.svg';
import Icon_city_icons_icons_es_gijon from '@/city-icons/icons/es-gijon.svg';
import Icon_city_icons_icons_es_granada from '@/city-icons/icons/es-granada.svg';
import Icon_city_icons_icons_es_madrid from '@/city-icons/icons/es-madrid.svg';
import Icon_city_icons_icons_es_malaga from '@/city-icons/icons/es-malaga.svg';
import Icon_city_icons_icons_es_santiago_de_compostela from '@/city-icons/icons/es-santiago-de-compostela.svg';
import Icon_city_icons_icons_es_valencia from '@/city-icons/icons/es-valencia.svg';
import Icon_city_icons_icons_es_vigo from '@/city-icons/icons/es-vigo.svg';
import Icon_city_icons_icons_et_lalibela from '@/city-icons/icons/et-lalibela.svg';
import Icon_city_icons_icons_fi_helsinki from '@/city-icons/icons/fi-helsinki.svg';
import Icon_city_icons_icons_fi_kuopio from '@/city-icons/icons/fi-kuopio.svg';
import Icon_city_icons_icons_fj_suva from '@/city-icons/icons/fj-suva.svg';
import Icon_city_icons_icons_fr_bordeaux from '@/city-icons/icons/fr-bordeaux.svg';
import Icon_city_icons_icons_fr_lyon from '@/city-icons/icons/fr-lyon.svg';
import Icon_city_icons_icons_fr_montpellier from '@/city-icons/icons/fr-montpellier.svg';
import Icon_city_icons_icons_fr_paris from '@/city-icons/icons/fr-paris.svg';
import Icon_city_icons_icons_fr_rennes from '@/city-icons/icons/fr-rennes.svg';
import Icon_city_icons_icons_fr_toulouse from '@/city-icons/icons/fr-toulouse.svg';
import Icon_city_icons_icons_gb_edinburgh from '@/city-icons/icons/gb-edinburgh.svg';
import Icon_city_icons_icons_gb_glasgow from '@/city-icons/icons/gb-glasgow.svg';
import Icon_city_icons_icons_gb_leeds from '@/city-icons/icons/gb-leeds.svg';
import Icon_city_icons_icons_gb_liverpool from '@/city-icons/icons/gb-liverpool.svg';
import Icon_city_icons_icons_gb_london from '@/city-icons/icons/gb-london.svg';
import Icon_city_icons_icons_gb_manchester from '@/city-icons/icons/gb-manchester.svg';
import Icon_city_icons_icons_gd_st_george from '@/city-icons/icons/gd-st-george.svg';
import Icon_city_icons_icons_ge_batumi from '@/city-icons/icons/ge-batumi.svg';
import Icon_city_icons_icons_ge_kutaisi from '@/city-icons/icons/ge-kutaisi.svg';
import Icon_city_icons_icons_ge_tbilisi from '@/city-icons/icons/ge-tbilisi.svg';
import Icon_city_icons_icons_gh_accra from '@/city-icons/icons/gh-accra.svg';
import Icon_city_icons_icons_gi_gibraltar from '@/city-icons/icons/gi-gibraltar.svg';
import Icon_city_icons_icons_gr_athens from '@/city-icons/icons/gr-athens.svg';
import Icon_city_icons_icons_gt_antigua from '@/city-icons/icons/gt-antigua.svg';
import Icon_city_icons_icons_gy_georgetown from '@/city-icons/icons/gy-georgetown.svg';
import Icon_city_icons_icons_hn_tegucigalpa from '@/city-icons/icons/hn-tegucigalpa.svg';
import Icon_city_icons_icons_hr_zagreb from '@/city-icons/icons/hr-zagreb.svg';
import Icon_city_icons_icons_ht_port_au_prince from '@/city-icons/icons/ht-port-au-prince.svg';
import Icon_city_icons_icons_hu_budapest from '@/city-icons/icons/hu-budapest.svg';
import Icon_city_icons_icons_hu_debrecen from '@/city-icons/icons/hu-debrecen.svg';
import Icon_city_icons_icons_hu_szeged from '@/city-icons/icons/hu-szeged.svg';
import Icon_city_icons_icons_id_denpasar from '@/city-icons/icons/id-denpasar.svg';
import Icon_city_icons_icons_ie_dublin from '@/city-icons/icons/ie-dublin.svg';
import Icon_city_icons_icons_il_haifa from '@/city-icons/icons/il-haifa.svg';
import Icon_city_icons_icons_il_jerusalem from '@/city-icons/icons/il-jerusalem.svg';
import Icon_city_icons_icons_il_tel_aviv from '@/city-icons/icons/il-tel-aviv.svg';
import Icon_city_icons_icons_in_agra from '@/city-icons/icons/in-agra.svg';
import Icon_city_icons_icons_in_delhi from '@/city-icons/icons/in-delhi.svg';
import Icon_city_icons_icons_iq_samarra from '@/city-icons/icons/iq-samarra.svg';
import Icon_city_icons_icons_ir_isfahan from '@/city-icons/icons/ir-isfahan.svg';
import Icon_city_icons_icons_ir_mashhad from '@/city-icons/icons/ir-mashhad.svg';
import Icon_city_icons_icons_ir_tehran from '@/city-icons/icons/ir-tehran.svg';
import Icon_city_icons_icons_is_akureyri from '@/city-icons/icons/is-akureyri.svg';
import Icon_city_icons_icons_is_reykjavik from '@/city-icons/icons/is-reykjavik.svg';
import Icon_city_icons_icons_it_bologna from '@/city-icons/icons/it-bologna.svg';
import Icon_city_icons_icons_it_ferrara from '@/city-icons/icons/it-ferrara.svg';
import Icon_city_icons_icons_it_forte_dei_marmi from '@/city-icons/icons/it-forte-dei-marmi.svg';
import Icon_city_icons_icons_it_milan from '@/city-icons/icons/it-milan.svg';
import Icon_city_icons_icons_it_palermo from '@/city-icons/icons/it-palermo.svg';
import Icon_city_icons_icons_it_rome from '@/city-icons/icons/it-rome.svg';
import Icon_city_icons_icons_it_sorrento from '@/city-icons/icons/it-sorrento.svg';
import Icon_city_icons_icons_it_taranto from '@/city-icons/icons/it-taranto.svg';
import Icon_city_icons_icons_it_trieste from '@/city-icons/icons/it-trieste.svg';
import Icon_city_icons_icons_it_venice from '@/city-icons/icons/it-venice.svg';
import Icon_city_icons_icons_jo_amman from '@/city-icons/icons/jo-amman.svg';
import Icon_city_icons_icons_jp_kyoto from '@/city-icons/icons/jp-kyoto.svg';
import Icon_city_icons_icons_jp_nara from '@/city-icons/icons/jp-nara.svg';
import Icon_city_icons_icons_jp_shirakawa_go from '@/city-icons/icons/jp-shirakawa-go.svg';
import Icon_city_icons_icons_jp_tokyo from '@/city-icons/icons/jp-tokyo.svg';
import Icon_city_icons_icons_ke_nairobi from '@/city-icons/icons/ke-nairobi.svg';
import Icon_city_icons_icons_kg_bishkek from '@/city-icons/icons/kg-bishkek.svg';
import Icon_city_icons_icons_kh_sihanoukville from '@/city-icons/icons/kh-sihanoukville.svg';
import Icon_city_icons_icons_ki_tarawa from '@/city-icons/icons/ki-tarawa.svg';
import Icon_city_icons_icons_kp_pyongyang from '@/city-icons/icons/kp-pyongyang.svg';
import Icon_city_icons_icons_kr_seoul from '@/city-icons/icons/kr-seoul.svg';
import Icon_city_icons_icons_kw_kuwait from '@/city-icons/icons/kw-kuwait.svg';
import Icon_city_icons_icons_kz_alma_aty from '@/city-icons/icons/kz-alma-aty.svg';
import Icon_city_icons_icons_kz_astana from '@/city-icons/icons/kz-astana.svg';
import Icon_city_icons_icons_kz_karaganda from '@/city-icons/icons/kz-karaganda.svg';
import Icon_city_icons_icons_kz_kostanay from '@/city-icons/icons/kz-kostanay.svg';
import Icon_city_icons_icons_kz_schuchinsk from '@/city-icons/icons/kz-schuchinsk.svg';
import Icon_city_icons_icons_kz_uralsk from '@/city-icons/icons/kz-uralsk.svg';
import Icon_city_icons_icons_la_luang_prabang from '@/city-icons/icons/la-luang-prabang.svg';
import Icon_city_icons_icons_lb_beirut from '@/city-icons/icons/lb-beirut.svg';
import Icon_city_icons_icons_lc_soufriere from '@/city-icons/icons/lc-soufriere.svg';
import Icon_city_icons_icons_li_vaduz from '@/city-icons/icons/li-vaduz.svg';
import Icon_city_icons_icons_ls_maseru from '@/city-icons/icons/ls-maseru.svg';
import Icon_city_icons_icons_lt_vilnius from '@/city-icons/icons/lt-vilnius.svg';
import Icon_city_icons_icons_lu_luxembourg from '@/city-icons/icons/lu-luxembourg.svg';
import Icon_city_icons_icons_lv_riga from '@/city-icons/icons/lv-riga.svg';
import Icon_city_icons_icons_ly_benghazi from '@/city-icons/icons/ly-benghazi.svg';
import Icon_city_icons_icons_ma_casablanca from '@/city-icons/icons/ma-casablanca.svg';
import Icon_city_icons_icons_ma_fez from '@/city-icons/icons/ma-fez.svg';
import Icon_city_icons_icons_ma_marrakesh from '@/city-icons/icons/ma-marrakesh.svg';
import Icon_city_icons_icons_mc_monaco from '@/city-icons/icons/mc-monaco.svg';
import Icon_city_icons_icons_md_chisinau from '@/city-icons/icons/md-chisinau.svg';
import Icon_city_icons_icons_me_budva from '@/city-icons/icons/me-budva.svg';
import Icon_city_icons_icons_me_herceg_novi from '@/city-icons/icons/me-herceg-novi.svg';
import Icon_city_icons_icons_me_podgorica from '@/city-icons/icons/me-podgorica.svg';
import Icon_city_icons_icons_mg_antananarivo from '@/city-icons/icons/mg-antananarivo.svg';
import Icon_city_icons_icons_mk_skopje from '@/city-icons/icons/mk-skopje.svg';
import Icon_city_icons_icons_ml_timbuktu from '@/city-icons/icons/ml-timbuktu.svg';
import Icon_city_icons_icons_mm_bagan from '@/city-icons/icons/mm-bagan.svg';
import Icon_city_icons_icons_mn_ulaanbaatar from '@/city-icons/icons/mn-ulaanbaatar.svg';
import Icon_city_icons_icons_mt_valletta from '@/city-icons/icons/mt-valletta.svg';
import Icon_city_icons_icons_mu_port_louis from '@/city-icons/icons/mu-port-louis.svg';
import Icon_city_icons_icons_mx_guadalajara from '@/city-icons/icons/mx-guadalajara.svg';
import Icon_city_icons_icons_mx_tijuana from '@/city-icons/icons/mx-tijuana.svg';
import Icon_city_icons_icons_my_kuala_lumpur from '@/city-icons/icons/my-kuala-lumpur.svg';
import Icon_city_icons_icons_my_kuching from '@/city-icons/icons/my-kuching.svg';
import Icon_city_icons_icons_mz_maputo from '@/city-icons/icons/mz-maputo.svg';
import Icon_city_icons_icons_na_windhoek from '@/city-icons/icons/na-windhoek.svg';
import Icon_city_icons_icons_nc_noumea from '@/city-icons/icons/nc-noumea.svg';
import Icon_city_icons_icons_ng_lagos from '@/city-icons/icons/ng-lagos.svg';
import Icon_city_icons_icons_ni_granada from '@/city-icons/icons/ni-granada.svg';
import Icon_city_icons_icons_nl_amsterdam from '@/city-icons/icons/nl-amsterdam.svg';
import Icon_city_icons_icons_nl_de_meije from '@/city-icons/icons/nl-de-meije.svg';
import Icon_city_icons_icons_nl_maastricht from '@/city-icons/icons/nl-maastricht.svg';
import Icon_city_icons_icons_nl_rotterdam from '@/city-icons/icons/nl-rotterdam.svg';
import Icon_city_icons_icons_nl_woerden from '@/city-icons/icons/nl-woerden.svg';
import Icon_city_icons_icons_no_oslo from '@/city-icons/icons/no-oslo.svg';
import Icon_city_icons_icons_np_kathmandu from '@/city-icons/icons/np-kathmandu.svg';
import Icon_city_icons_icons_nz_wellington from '@/city-icons/icons/nz-wellington.svg';
import Icon_city_icons_icons_om_muscat from '@/city-icons/icons/om-muscat.svg';
import Icon_city_icons_icons_pa_panama from '@/city-icons/icons/pa-panama.svg';
import Icon_city_icons_icons_pe_cusco from '@/city-icons/icons/pe-cusco.svg';
import Icon_city_icons_icons_pe_lima from '@/city-icons/icons/pe-lima.svg';
import Icon_city_icons_icons_ph_cebu from '@/city-icons/icons/ph-cebu.svg';
import Icon_city_icons_icons_ph_manila from '@/city-icons/icons/ph-manila.svg';
import Icon_city_icons_icons_pk_islamabad from '@/city-icons/icons/pk-islamabad.svg';
import Icon_city_icons_icons_pk_karachi from '@/city-icons/icons/pk-karachi.svg';
import Icon_city_icons_icons_pl_gdansk from '@/city-icons/icons/pl-gdansk.svg';
import Icon_city_icons_icons_pl_krakow from '@/city-icons/icons/pl-krakow.svg';
import Icon_city_icons_icons_pl_poznan from '@/city-icons/icons/pl-poznan.svg';
import Icon_city_icons_icons_pl_swiebodzin from '@/city-icons/icons/pl-swiebodzin.svg';
import Icon_city_icons_icons_pl_warsaw from '@/city-icons/icons/pl-warsaw.svg';
import Icon_city_icons_icons_pl_wroclaw from '@/city-icons/icons/pl-wroclaw.svg';
import Icon_city_icons_icons_pr_san_juan from '@/city-icons/icons/pr-san-juan.svg';
import Icon_city_icons_icons_ps_jerusalem from '@/city-icons/icons/ps-jerusalem.svg';
import Icon_city_icons_icons_pt_amadora from '@/city-icons/icons/pt-amadora.svg';
import Icon_city_icons_icons_pt_barcelos from '@/city-icons/icons/pt-barcelos.svg';
import Icon_city_icons_icons_pt_braga from '@/city-icons/icons/pt-braga.svg';
import Icon_city_icons_icons_pt_chaves from '@/city-icons/icons/pt-chaves.svg';
import Icon_city_icons_icons_pt_guimaraes from '@/city-icons/icons/pt-guimaraes.svg';
import Icon_city_icons_icons_pt_leiria from '@/city-icons/icons/pt-leiria.svg';
import Icon_city_icons_icons_pt_lisbon from '@/city-icons/icons/pt-lisbon.svg';
import Icon_city_icons_icons_pt_matosinhos from '@/city-icons/icons/pt-matosinhos.svg';
import Icon_city_icons_icons_pt_nazare from '@/city-icons/icons/pt-nazare.svg';
import Icon_city_icons_icons_pt_porto from '@/city-icons/icons/pt-porto.svg';
import Icon_city_icons_icons_pt_viana_do_castelo from '@/city-icons/icons/pt-viana-do-castelo.svg';
import Icon_city_icons_icons_pt_vila_real from '@/city-icons/icons/pt-vila-real.svg';
import Icon_city_icons_icons_qa_doha from '@/city-icons/icons/qa-doha.svg';
import Icon_city_icons_icons_ro_bucharest from '@/city-icons/icons/ro-bucharest.svg';
import Icon_city_icons_icons_ro_sibiu from '@/city-icons/icons/ro-sibiu.svg';
import Icon_city_icons_icons_rs_belgrade from '@/city-icons/icons/rs-belgrade.svg';
import Icon_city_icons_icons_rs_subotica from '@/city-icons/icons/rs-subotica.svg';
import Icon_city_icons_icons_ru_moscow from '@/city-icons/icons/ru-moscow.svg';
import Icon_city_icons_icons_ru_murmansk from '@/city-icons/icons/ru-murmansk.svg';
import Icon_city_icons_icons_ru_tula from '@/city-icons/icons/ru-tula.svg';
import Icon_city_icons_icons_ru_yakutsk from '@/city-icons/icons/ru-yakutsk.svg';
import Icon_city_icons_icons_rw_kigali from '@/city-icons/icons/rw-kigali.svg';
import Icon_city_icons_icons_sa_riyadh from '@/city-icons/icons/sa-riyadh.svg';
import Icon_city_icons_icons_sb_honiara from '@/city-icons/icons/sb-honiara.svg';
import Icon_city_icons_icons_sd_meroe from '@/city-icons/icons/sd-meroe.svg';
import Icon_city_icons_icons_se_stockholm from '@/city-icons/icons/se-stockholm.svg';
import Icon_city_icons_icons_sg_sentosa from '@/city-icons/icons/sg-sentosa.svg';
import Icon_city_icons_icons_si_ljubljana from '@/city-icons/icons/si-ljubljana.svg';
import Icon_city_icons_icons_sj_longyearbyen from '@/city-icons/icons/sj-longyearbyen.svg';
import Icon_city_icons_icons_sk_bratislava from '@/city-icons/icons/sk-bratislava.svg';
import Icon_city_icons_icons_sm_san_marino from '@/city-icons/icons/sm-san-marino.svg';
import Icon_city_icons_icons_sn_dakar from '@/city-icons/icons/sn-dakar.svg';
import Icon_city_icons_icons_st_sao_tome from '@/city-icons/icons/st-sao-tome.svg';
import Icon_city_icons_icons_sv_san_salvador from '@/city-icons/icons/sv-san-salvador.svg';
import Icon_city_icons_icons_th_pattaya from '@/city-icons/icons/th-pattaya.svg';
import Icon_city_icons_icons_tj_dushanbe from '@/city-icons/icons/tj-dushanbe.svg';
import Icon_city_icons_icons_tl_dili from '@/city-icons/icons/tl-dili.svg';
import Icon_city_icons_icons_tm_ashgabat from '@/city-icons/icons/tm-ashgabat.svg';
import Icon_city_icons_icons_tn_tunis from '@/city-icons/icons/tn-tunis.svg';
import Icon_city_icons_icons_to_nukualofa from '@/city-icons/icons/to-nukualofa.svg';
import Icon_city_icons_icons_tr_ankara from '@/city-icons/icons/tr-ankara.svg';
import Icon_city_icons_icons_tr_antalya from '@/city-icons/icons/tr-antalya.svg';
import Icon_city_icons_icons_tr_istanbul from '@/city-icons/icons/tr-istanbul.svg';
import Icon_city_icons_icons_tr_izmir from '@/city-icons/icons/tr-izmir.svg';
import Icon_city_icons_icons_tv_funafuti from '@/city-icons/icons/tv-funafuti.svg';
import Icon_city_icons_icons_tw_taipei from '@/city-icons/icons/tw-taipei.svg';
import Icon_city_icons_icons_tz_zanzibar from '@/city-icons/icons/tz-zanzibar.svg';
import Icon_city_icons_icons_ua_kyiv from '@/city-icons/icons/ua-kyiv.svg';
import Icon_city_icons_icons_ua_odessa from '@/city-icons/icons/ua-odessa.svg';
import Icon_city_icons_icons_us_albuquerque from '@/city-icons/icons/us-albuquerque.svg';
import Icon_city_icons_icons_us_atlanta from '@/city-icons/icons/us-atlanta.svg';
import Icon_city_icons_icons_us_austin from '@/city-icons/icons/us-austin.svg';
import Icon_city_icons_icons_us_boston from '@/city-icons/icons/us-boston.svg';
import Icon_city_icons_icons_us_chicago from '@/city-icons/icons/us-chicago.svg';
import Icon_city_icons_icons_us_cincinnati from '@/city-icons/icons/us-cincinnati.svg';
import Icon_city_icons_icons_us_columbus from '@/city-icons/icons/us-columbus.svg';
import Icon_city_icons_icons_us_denver from '@/city-icons/icons/us-denver.svg';
import Icon_city_icons_icons_us_hartford from '@/city-icons/icons/us-hartford.svg';
import Icon_city_icons_icons_us_irvine from '@/city-icons/icons/us-irvine.svg';
import Icon_city_icons_icons_us_los_angeles from '@/city-icons/icons/us-los-angeles.svg';
import Icon_city_icons_icons_us_miami from '@/city-icons/icons/us-miami.svg';
import Icon_city_icons_icons_us_new_orleans from '@/city-icons/icons/us-new-orleans.svg';
import Icon_city_icons_icons_us_new_york from '@/city-icons/icons/us-new-york.svg';
import Icon_city_icons_icons_us_peoria from '@/city-icons/icons/us-peoria.svg';
import Icon_city_icons_icons_us_philadelphia from '@/city-icons/icons/us-philadelphia.svg';
import Icon_city_icons_icons_us_phoenix from '@/city-icons/icons/us-phoenix.svg';
import Icon_city_icons_icons_us_pittsburgh from '@/city-icons/icons/us-pittsburgh.svg';
import Icon_city_icons_icons_us_sacramento from '@/city-icons/icons/us-sacramento.svg';
import Icon_city_icons_icons_us_san_diego from '@/city-icons/icons/us-san-diego.svg';
import Icon_city_icons_icons_us_san_francisco from '@/city-icons/icons/us-san-francisco.svg';
import Icon_city_icons_icons_us_seattle from '@/city-icons/icons/us-seattle.svg';
import Icon_city_icons_icons_us_st_louis from '@/city-icons/icons/us-st-louis.svg';
import Icon_city_icons_icons_us_washington from '@/city-icons/icons/us-washington.svg';
import Icon_city_icons_icons_uy_montevideo from '@/city-icons/icons/uy-montevideo.svg';
import Icon_city_icons_icons_uz_nukus from '@/city-icons/icons/uz-nukus.svg';
import Icon_city_icons_icons_uz_tashkent from '@/city-icons/icons/uz-tashkent.svg';
import Icon_city_icons_icons_va_vatican from '@/city-icons/icons/va-vatican.svg';
import Icon_city_icons_icons_ve_caracas from '@/city-icons/icons/ve-caracas.svg';
import Icon_city_icons_icons_vn_da_nang from '@/city-icons/icons/vn-da-nang.svg';
import Icon_city_icons_icons_vn_hanoi_temple_of_literature from '@/city-icons/icons/vn-hanoi-temple-of-literature.svg';
import Icon_city_icons_icons_vn_hanoi from '@/city-icons/icons/vn-hanoi.svg';
import Icon_city_icons_icons_vn_ho_chi_minh from '@/city-icons/icons/vn-ho-chi-minh.svg';
import Icon_city_icons_icons_vn_vung_tau from '@/city-icons/icons/vn-vung-tau.svg';
import Icon_city_icons_icons_vu_port_vila from '@/city-icons/icons/vu-port-vila.svg';
import Icon_city_icons_icons_ws_apia from '@/city-icons/icons/ws-apia.svg';
import Icon_city_icons_icons_xk_pristina from '@/city-icons/icons/xk-pristina.svg';
import Icon_city_icons_icons_za_cape_town from '@/city-icons/icons/za-cape-town.svg';

export type BoardIcon = FC<SvgProps>;

export const iconRegistry: Record<string, BoardIcon> = {
  'city-icons/generic/arrow-narrow-right.svg': Icon_city_icons_generic_arrow_narrow_right,
  'city-icons/generic/bolt.svg': Icon_city_icons_generic_bolt,
  'city-icons/generic/building-castle.svg': Icon_city_icons_generic_building_castle,
  'city-icons/generic/droplet.svg': Icon_city_icons_generic_droplet,
  'city-icons/generic/handcuffs.svg': Icon_city_icons_generic_handcuffs,
  'city-icons/generic/parking.svg': Icon_city_icons_generic_parking,
  'city-icons/generic/plane-tilt.svg': Icon_city_icons_generic_plane_tilt,
  'city-icons/generic/prison.svg': Icon_city_icons_generic_prison,
  'city-icons/generic/question-mark.svg': Icon_city_icons_generic_question_mark,
  'city-icons/generic/receipt-tax.svg': Icon_city_icons_generic_receipt_tax,
  'city-icons/generic/tax.svg': Icon_city_icons_generic_tax,
  'city-icons/generic/treasure-chest.svg': Icon_city_icons_generic_treasure_chest,
  'city-icons/icons/ad-andorra.svg': Icon_city_icons_icons_ad_andorra,
  'city-icons/icons/ae-abu-dhabi.svg': Icon_city_icons_icons_ae_abu_dhabi,
  'city-icons/icons/ae-dubai.svg': Icon_city_icons_icons_ae_dubai,
  'city-icons/icons/ag-saint-john.svg': Icon_city_icons_icons_ag_saint_john,
  'city-icons/icons/al-tirana.svg': Icon_city_icons_icons_al_tirana,
  'city-icons/icons/am-yerevan.svg': Icon_city_icons_icons_am_yerevan,
  'city-icons/icons/ar-buenos-aires.svg': Icon_city_icons_icons_ar_buenos_aires,
  'city-icons/icons/ar-cordoba.svg': Icon_city_icons_icons_ar_cordoba,
  'city-icons/icons/ar-ushuaia.svg': Icon_city_icons_icons_ar_ushuaia,
  'city-icons/icons/at-graz.svg': Icon_city_icons_icons_at_graz,
  'city-icons/icons/at-hallstatt.svg': Icon_city_icons_icons_at_hallstatt,
  'city-icons/icons/at-vienna.svg': Icon_city_icons_icons_at_vienna,
  'city-icons/icons/au-canberra.svg': Icon_city_icons_icons_au_canberra,
  'city-icons/icons/au-hobart.svg': Icon_city_icons_icons_au_hobart,
  'city-icons/icons/au-melbourne.svg': Icon_city_icons_icons_au_melbourne,
  'city-icons/icons/au-perth.svg': Icon_city_icons_icons_au_perth,
  'city-icons/icons/au-sydney.svg': Icon_city_icons_icons_au_sydney,
  'city-icons/icons/az-baku.svg': Icon_city_icons_icons_az_baku,
  'city-icons/icons/ba-mostar.svg': Icon_city_icons_icons_ba_mostar,
  'city-icons/icons/ba-sarajevo.svg': Icon_city_icons_icons_ba_sarajevo,
  'city-icons/icons/bd-dhaka.svg': Icon_city_icons_icons_bd_dhaka,
  'city-icons/icons/be-bruges.svg': Icon_city_icons_icons_be_bruges,
  'city-icons/icons/be-brussels.svg': Icon_city_icons_icons_be_brussels,
  'city-icons/icons/bf-ouagadougou.svg': Icon_city_icons_icons_bf_ouagadougou,
  'city-icons/icons/bg-burgas.svg': Icon_city_icons_icons_bg_burgas,
  'city-icons/icons/bg-sofia.svg': Icon_city_icons_icons_bg_sofia,
  'city-icons/icons/bh-manama.svg': Icon_city_icons_icons_bh_manama,
  'city-icons/icons/bn-seria.svg': Icon_city_icons_icons_bn_seria,
  'city-icons/icons/bo-la-paz.svg': Icon_city_icons_icons_bo_la_paz,
  'city-icons/icons/br-brasilia.svg': Icon_city_icons_icons_br_brasilia,
  'city-icons/icons/br-rio-de-janeiro.svg': Icon_city_icons_icons_br_rio_de_janeiro,
  'city-icons/icons/br-sao-paulo-masp.svg': Icon_city_icons_icons_br_sao_paulo_masp,
  'city-icons/icons/br-sao-paulo.svg': Icon_city_icons_icons_br_sao_paulo,
  'city-icons/icons/bs-nassau.svg': Icon_city_icons_icons_bs_nassau,
  'city-icons/icons/bt-thimphu.svg': Icon_city_icons_icons_bt_thimphu,
  'city-icons/icons/by-minsk.svg': Icon_city_icons_icons_by_minsk,
  'city-icons/icons/bz-san-ignacio.svg': Icon_city_icons_icons_bz_san_ignacio,
  'city-icons/icons/ca-ottawa.svg': Icon_city_icons_icons_ca_ottawa,
  'city-icons/icons/ca-toronto.svg': Icon_city_icons_icons_ca_toronto,
  'city-icons/icons/ca-vancouver.svg': Icon_city_icons_icons_ca_vancouver,
  'city-icons/icons/ch-bern.svg': Icon_city_icons_icons_ch_bern,
  'city-icons/icons/ci-yamoussoukro.svg': Icon_city_icons_icons_ci_yamoussoukro,
  'city-icons/icons/cl-santiago.svg': Icon_city_icons_icons_cl_santiago,
  'city-icons/icons/cl-valparaiso.svg': Icon_city_icons_icons_cl_valparaiso,
  'city-icons/icons/cn-beijing.svg': Icon_city_icons_icons_cn_beijing,
  'city-icons/icons/cn-chengdu.svg': Icon_city_icons_icons_cn_chengdu,
  'city-icons/icons/cn-jingzhou.svg': Icon_city_icons_icons_cn_jingzhou,
  'city-icons/icons/cn-leshan.svg': Icon_city_icons_icons_cn_leshan,
  'city-icons/icons/cn-shanghai.svg': Icon_city_icons_icons_cn_shanghai,
  'city-icons/icons/co-bogota.svg': Icon_city_icons_icons_co_bogota,
  'city-icons/icons/co-cartagena.svg': Icon_city_icons_icons_co_cartagena,
  'city-icons/icons/co-medellin.svg': Icon_city_icons_icons_co_medellin,
  'city-icons/icons/cr-alajuela.svg': Icon_city_icons_icons_cr_alajuela,
  'city-icons/icons/cu-havana.svg': Icon_city_icons_icons_cu_havana,
  'city-icons/icons/cw-willemstadt.svg': Icon_city_icons_icons_cw_willemstadt,
  'city-icons/icons/cy-limassol.svg': Icon_city_icons_icons_cy_limassol,
  'city-icons/icons/cy-nicosia.svg': Icon_city_icons_icons_cy_nicosia,
  'city-icons/icons/cy-paphos.svg': Icon_city_icons_icons_cy_paphos,
  'city-icons/icons/cz-prague.svg': Icon_city_icons_icons_cz_prague,
  'city-icons/icons/de-aachen.svg': Icon_city_icons_icons_de_aachen,
  'city-icons/icons/de-berlin.svg': Icon_city_icons_icons_de_berlin,
  'city-icons/icons/de-bielefeld.svg': Icon_city_icons_icons_de_bielefeld,
  'city-icons/icons/de-bremen.svg': Icon_city_icons_icons_de_bremen,
  'city-icons/icons/de-cologne.svg': Icon_city_icons_icons_de_cologne,
  'city-icons/icons/de-erfurt.svg': Icon_city_icons_icons_de_erfurt,
  'city-icons/icons/de-frankfurt.svg': Icon_city_icons_icons_de_frankfurt,
  'city-icons/icons/de-freiburg.svg': Icon_city_icons_icons_de_freiburg,
  'city-icons/icons/de-giessen.svg': Icon_city_icons_icons_de_giessen,
  'city-icons/icons/de-hamburg.svg': Icon_city_icons_icons_de_hamburg,
  'city-icons/icons/de-karlsruhe.svg': Icon_city_icons_icons_de_karlsruhe,
  'city-icons/icons/de-leipzig.svg': Icon_city_icons_icons_de_leipzig,
  'city-icons/icons/de-leverkusen.svg': Icon_city_icons_icons_de_leverkusen,
  'city-icons/icons/de-munich.svg': Icon_city_icons_icons_de_munich,
  'city-icons/icons/de-nuremberg.svg': Icon_city_icons_icons_de_nuremberg,
  'city-icons/icons/de-siegen.svg': Icon_city_icons_icons_de_siegen,
  'city-icons/icons/de-stuttgart.svg': Icon_city_icons_icons_de_stuttgart,
  'city-icons/icons/dk-copenhagen.svg': Icon_city_icons_icons_dk_copenhagen,
  'city-icons/icons/ec-quito.svg': Icon_city_icons_icons_ec_quito,
  'city-icons/icons/ee-tallinn.svg': Icon_city_icons_icons_ee_tallinn,
  'city-icons/icons/eg-cairo.svg': Icon_city_icons_icons_eg_cairo,
  'city-icons/icons/er-asmara.svg': Icon_city_icons_icons_er_asmara,
  'city-icons/icons/es-barcelona.svg': Icon_city_icons_icons_es_barcelona,
  'city-icons/icons/es-cordoba.svg': Icon_city_icons_icons_es_cordoba,
  'city-icons/icons/es-coruna.svg': Icon_city_icons_icons_es_coruna,
  'city-icons/icons/es-gijon.svg': Icon_city_icons_icons_es_gijon,
  'city-icons/icons/es-granada.svg': Icon_city_icons_icons_es_granada,
  'city-icons/icons/es-madrid.svg': Icon_city_icons_icons_es_madrid,
  'city-icons/icons/es-malaga.svg': Icon_city_icons_icons_es_malaga,
  'city-icons/icons/es-santiago-de-compostela.svg': Icon_city_icons_icons_es_santiago_de_compostela,
  'city-icons/icons/es-valencia.svg': Icon_city_icons_icons_es_valencia,
  'city-icons/icons/es-vigo.svg': Icon_city_icons_icons_es_vigo,
  'city-icons/icons/et-lalibela.svg': Icon_city_icons_icons_et_lalibela,
  'city-icons/icons/fi-helsinki.svg': Icon_city_icons_icons_fi_helsinki,
  'city-icons/icons/fi-kuopio.svg': Icon_city_icons_icons_fi_kuopio,
  'city-icons/icons/fj-suva.svg': Icon_city_icons_icons_fj_suva,
  'city-icons/icons/fr-bordeaux.svg': Icon_city_icons_icons_fr_bordeaux,
  'city-icons/icons/fr-lyon.svg': Icon_city_icons_icons_fr_lyon,
  'city-icons/icons/fr-montpellier.svg': Icon_city_icons_icons_fr_montpellier,
  'city-icons/icons/fr-paris.svg': Icon_city_icons_icons_fr_paris,
  'city-icons/icons/fr-rennes.svg': Icon_city_icons_icons_fr_rennes,
  'city-icons/icons/fr-toulouse.svg': Icon_city_icons_icons_fr_toulouse,
  'city-icons/icons/gb-edinburgh.svg': Icon_city_icons_icons_gb_edinburgh,
  'city-icons/icons/gb-glasgow.svg': Icon_city_icons_icons_gb_glasgow,
  'city-icons/icons/gb-leeds.svg': Icon_city_icons_icons_gb_leeds,
  'city-icons/icons/gb-liverpool.svg': Icon_city_icons_icons_gb_liverpool,
  'city-icons/icons/gb-london.svg': Icon_city_icons_icons_gb_london,
  'city-icons/icons/gb-manchester.svg': Icon_city_icons_icons_gb_manchester,
  'city-icons/icons/gd-st-george.svg': Icon_city_icons_icons_gd_st_george,
  'city-icons/icons/ge-batumi.svg': Icon_city_icons_icons_ge_batumi,
  'city-icons/icons/ge-kutaisi.svg': Icon_city_icons_icons_ge_kutaisi,
  'city-icons/icons/ge-tbilisi.svg': Icon_city_icons_icons_ge_tbilisi,
  'city-icons/icons/gh-accra.svg': Icon_city_icons_icons_gh_accra,
  'city-icons/icons/gi-gibraltar.svg': Icon_city_icons_icons_gi_gibraltar,
  'city-icons/icons/gr-athens.svg': Icon_city_icons_icons_gr_athens,
  'city-icons/icons/gt-antigua.svg': Icon_city_icons_icons_gt_antigua,
  'city-icons/icons/gy-georgetown.svg': Icon_city_icons_icons_gy_georgetown,
  'city-icons/icons/hn-tegucigalpa.svg': Icon_city_icons_icons_hn_tegucigalpa,
  'city-icons/icons/hr-zagreb.svg': Icon_city_icons_icons_hr_zagreb,
  'city-icons/icons/ht-port-au-prince.svg': Icon_city_icons_icons_ht_port_au_prince,
  'city-icons/icons/hu-budapest.svg': Icon_city_icons_icons_hu_budapest,
  'city-icons/icons/hu-debrecen.svg': Icon_city_icons_icons_hu_debrecen,
  'city-icons/icons/hu-szeged.svg': Icon_city_icons_icons_hu_szeged,
  'city-icons/icons/id-denpasar.svg': Icon_city_icons_icons_id_denpasar,
  'city-icons/icons/ie-dublin.svg': Icon_city_icons_icons_ie_dublin,
  'city-icons/icons/il-haifa.svg': Icon_city_icons_icons_il_haifa,
  'city-icons/icons/il-jerusalem.svg': Icon_city_icons_icons_il_jerusalem,
  'city-icons/icons/il-tel-aviv.svg': Icon_city_icons_icons_il_tel_aviv,
  'city-icons/icons/in-agra.svg': Icon_city_icons_icons_in_agra,
  'city-icons/icons/in-delhi.svg': Icon_city_icons_icons_in_delhi,
  'city-icons/icons/iq-samarra.svg': Icon_city_icons_icons_iq_samarra,
  'city-icons/icons/ir-isfahan.svg': Icon_city_icons_icons_ir_isfahan,
  'city-icons/icons/ir-mashhad.svg': Icon_city_icons_icons_ir_mashhad,
  'city-icons/icons/ir-tehran.svg': Icon_city_icons_icons_ir_tehran,
  'city-icons/icons/is-akureyri.svg': Icon_city_icons_icons_is_akureyri,
  'city-icons/icons/is-reykjavik.svg': Icon_city_icons_icons_is_reykjavik,
  'city-icons/icons/it-bologna.svg': Icon_city_icons_icons_it_bologna,
  'city-icons/icons/it-ferrara.svg': Icon_city_icons_icons_it_ferrara,
  'city-icons/icons/it-forte-dei-marmi.svg': Icon_city_icons_icons_it_forte_dei_marmi,
  'city-icons/icons/it-milan.svg': Icon_city_icons_icons_it_milan,
  'city-icons/icons/it-palermo.svg': Icon_city_icons_icons_it_palermo,
  'city-icons/icons/it-rome.svg': Icon_city_icons_icons_it_rome,
  'city-icons/icons/it-sorrento.svg': Icon_city_icons_icons_it_sorrento,
  'city-icons/icons/it-taranto.svg': Icon_city_icons_icons_it_taranto,
  'city-icons/icons/it-trieste.svg': Icon_city_icons_icons_it_trieste,
  'city-icons/icons/it-venice.svg': Icon_city_icons_icons_it_venice,
  'city-icons/icons/jo-amman.svg': Icon_city_icons_icons_jo_amman,
  'city-icons/icons/jp-kyoto.svg': Icon_city_icons_icons_jp_kyoto,
  'city-icons/icons/jp-nara.svg': Icon_city_icons_icons_jp_nara,
  'city-icons/icons/jp-shirakawa-go.svg': Icon_city_icons_icons_jp_shirakawa_go,
  'city-icons/icons/jp-tokyo.svg': Icon_city_icons_icons_jp_tokyo,
  'city-icons/icons/ke-nairobi.svg': Icon_city_icons_icons_ke_nairobi,
  'city-icons/icons/kg-bishkek.svg': Icon_city_icons_icons_kg_bishkek,
  'city-icons/icons/kh-sihanoukville.svg': Icon_city_icons_icons_kh_sihanoukville,
  'city-icons/icons/ki-tarawa.svg': Icon_city_icons_icons_ki_tarawa,
  'city-icons/icons/kp-pyongyang.svg': Icon_city_icons_icons_kp_pyongyang,
  'city-icons/icons/kr-seoul.svg': Icon_city_icons_icons_kr_seoul,
  'city-icons/icons/kw-kuwait.svg': Icon_city_icons_icons_kw_kuwait,
  'city-icons/icons/kz-alma-aty.svg': Icon_city_icons_icons_kz_alma_aty,
  'city-icons/icons/kz-astana.svg': Icon_city_icons_icons_kz_astana,
  'city-icons/icons/kz-karaganda.svg': Icon_city_icons_icons_kz_karaganda,
  'city-icons/icons/kz-kostanay.svg': Icon_city_icons_icons_kz_kostanay,
  'city-icons/icons/kz-schuchinsk.svg': Icon_city_icons_icons_kz_schuchinsk,
  'city-icons/icons/kz-uralsk.svg': Icon_city_icons_icons_kz_uralsk,
  'city-icons/icons/la-luang-prabang.svg': Icon_city_icons_icons_la_luang_prabang,
  'city-icons/icons/lb-beirut.svg': Icon_city_icons_icons_lb_beirut,
  'city-icons/icons/lc-soufriere.svg': Icon_city_icons_icons_lc_soufriere,
  'city-icons/icons/li-vaduz.svg': Icon_city_icons_icons_li_vaduz,
  'city-icons/icons/ls-maseru.svg': Icon_city_icons_icons_ls_maseru,
  'city-icons/icons/lt-vilnius.svg': Icon_city_icons_icons_lt_vilnius,
  'city-icons/icons/lu-luxembourg.svg': Icon_city_icons_icons_lu_luxembourg,
  'city-icons/icons/lv-riga.svg': Icon_city_icons_icons_lv_riga,
  'city-icons/icons/ly-benghazi.svg': Icon_city_icons_icons_ly_benghazi,
  'city-icons/icons/ma-casablanca.svg': Icon_city_icons_icons_ma_casablanca,
  'city-icons/icons/ma-fez.svg': Icon_city_icons_icons_ma_fez,
  'city-icons/icons/ma-marrakesh.svg': Icon_city_icons_icons_ma_marrakesh,
  'city-icons/icons/mc-monaco.svg': Icon_city_icons_icons_mc_monaco,
  'city-icons/icons/md-chisinau.svg': Icon_city_icons_icons_md_chisinau,
  'city-icons/icons/me-budva.svg': Icon_city_icons_icons_me_budva,
  'city-icons/icons/me-herceg-novi.svg': Icon_city_icons_icons_me_herceg_novi,
  'city-icons/icons/me-podgorica.svg': Icon_city_icons_icons_me_podgorica,
  'city-icons/icons/mg-antananarivo.svg': Icon_city_icons_icons_mg_antananarivo,
  'city-icons/icons/mk-skopje.svg': Icon_city_icons_icons_mk_skopje,
  'city-icons/icons/ml-timbuktu.svg': Icon_city_icons_icons_ml_timbuktu,
  'city-icons/icons/mm-bagan.svg': Icon_city_icons_icons_mm_bagan,
  'city-icons/icons/mn-ulaanbaatar.svg': Icon_city_icons_icons_mn_ulaanbaatar,
  'city-icons/icons/mt-valletta.svg': Icon_city_icons_icons_mt_valletta,
  'city-icons/icons/mu-port-louis.svg': Icon_city_icons_icons_mu_port_louis,
  'city-icons/icons/mx-guadalajara.svg': Icon_city_icons_icons_mx_guadalajara,
  'city-icons/icons/mx-tijuana.svg': Icon_city_icons_icons_mx_tijuana,
  'city-icons/icons/my-kuala-lumpur.svg': Icon_city_icons_icons_my_kuala_lumpur,
  'city-icons/icons/my-kuching.svg': Icon_city_icons_icons_my_kuching,
  'city-icons/icons/mz-maputo.svg': Icon_city_icons_icons_mz_maputo,
  'city-icons/icons/na-windhoek.svg': Icon_city_icons_icons_na_windhoek,
  'city-icons/icons/nc-noumea.svg': Icon_city_icons_icons_nc_noumea,
  'city-icons/icons/ng-lagos.svg': Icon_city_icons_icons_ng_lagos,
  'city-icons/icons/ni-granada.svg': Icon_city_icons_icons_ni_granada,
  'city-icons/icons/nl-amsterdam.svg': Icon_city_icons_icons_nl_amsterdam,
  'city-icons/icons/nl-de-meije.svg': Icon_city_icons_icons_nl_de_meije,
  'city-icons/icons/nl-maastricht.svg': Icon_city_icons_icons_nl_maastricht,
  'city-icons/icons/nl-rotterdam.svg': Icon_city_icons_icons_nl_rotterdam,
  'city-icons/icons/nl-woerden.svg': Icon_city_icons_icons_nl_woerden,
  'city-icons/icons/no-oslo.svg': Icon_city_icons_icons_no_oslo,
  'city-icons/icons/np-kathmandu.svg': Icon_city_icons_icons_np_kathmandu,
  'city-icons/icons/nz-wellington.svg': Icon_city_icons_icons_nz_wellington,
  'city-icons/icons/om-muscat.svg': Icon_city_icons_icons_om_muscat,
  'city-icons/icons/pa-panama.svg': Icon_city_icons_icons_pa_panama,
  'city-icons/icons/pe-cusco.svg': Icon_city_icons_icons_pe_cusco,
  'city-icons/icons/pe-lima.svg': Icon_city_icons_icons_pe_lima,
  'city-icons/icons/ph-cebu.svg': Icon_city_icons_icons_ph_cebu,
  'city-icons/icons/ph-manila.svg': Icon_city_icons_icons_ph_manila,
  'city-icons/icons/pk-islamabad.svg': Icon_city_icons_icons_pk_islamabad,
  'city-icons/icons/pk-karachi.svg': Icon_city_icons_icons_pk_karachi,
  'city-icons/icons/pl-gdansk.svg': Icon_city_icons_icons_pl_gdansk,
  'city-icons/icons/pl-krakow.svg': Icon_city_icons_icons_pl_krakow,
  'city-icons/icons/pl-poznan.svg': Icon_city_icons_icons_pl_poznan,
  'city-icons/icons/pl-swiebodzin.svg': Icon_city_icons_icons_pl_swiebodzin,
  'city-icons/icons/pl-warsaw.svg': Icon_city_icons_icons_pl_warsaw,
  'city-icons/icons/pl-wroclaw.svg': Icon_city_icons_icons_pl_wroclaw,
  'city-icons/icons/pr-san-juan.svg': Icon_city_icons_icons_pr_san_juan,
  'city-icons/icons/ps-jerusalem.svg': Icon_city_icons_icons_ps_jerusalem,
  'city-icons/icons/pt-amadora.svg': Icon_city_icons_icons_pt_amadora,
  'city-icons/icons/pt-barcelos.svg': Icon_city_icons_icons_pt_barcelos,
  'city-icons/icons/pt-braga.svg': Icon_city_icons_icons_pt_braga,
  'city-icons/icons/pt-chaves.svg': Icon_city_icons_icons_pt_chaves,
  'city-icons/icons/pt-guimaraes.svg': Icon_city_icons_icons_pt_guimaraes,
  'city-icons/icons/pt-leiria.svg': Icon_city_icons_icons_pt_leiria,
  'city-icons/icons/pt-lisbon.svg': Icon_city_icons_icons_pt_lisbon,
  'city-icons/icons/pt-matosinhos.svg': Icon_city_icons_icons_pt_matosinhos,
  'city-icons/icons/pt-nazare.svg': Icon_city_icons_icons_pt_nazare,
  'city-icons/icons/pt-porto.svg': Icon_city_icons_icons_pt_porto,
  'city-icons/icons/pt-viana-do-castelo.svg': Icon_city_icons_icons_pt_viana_do_castelo,
  'city-icons/icons/pt-vila-real.svg': Icon_city_icons_icons_pt_vila_real,
  'city-icons/icons/qa-doha.svg': Icon_city_icons_icons_qa_doha,
  'city-icons/icons/ro-bucharest.svg': Icon_city_icons_icons_ro_bucharest,
  'city-icons/icons/ro-sibiu.svg': Icon_city_icons_icons_ro_sibiu,
  'city-icons/icons/rs-belgrade.svg': Icon_city_icons_icons_rs_belgrade,
  'city-icons/icons/rs-subotica.svg': Icon_city_icons_icons_rs_subotica,
  'city-icons/icons/ru-moscow.svg': Icon_city_icons_icons_ru_moscow,
  'city-icons/icons/ru-murmansk.svg': Icon_city_icons_icons_ru_murmansk,
  'city-icons/icons/ru-tula.svg': Icon_city_icons_icons_ru_tula,
  'city-icons/icons/ru-yakutsk.svg': Icon_city_icons_icons_ru_yakutsk,
  'city-icons/icons/rw-kigali.svg': Icon_city_icons_icons_rw_kigali,
  'city-icons/icons/sa-riyadh.svg': Icon_city_icons_icons_sa_riyadh,
  'city-icons/icons/sb-honiara.svg': Icon_city_icons_icons_sb_honiara,
  'city-icons/icons/sd-meroe.svg': Icon_city_icons_icons_sd_meroe,
  'city-icons/icons/se-stockholm.svg': Icon_city_icons_icons_se_stockholm,
  'city-icons/icons/sg-sentosa.svg': Icon_city_icons_icons_sg_sentosa,
  'city-icons/icons/si-ljubljana.svg': Icon_city_icons_icons_si_ljubljana,
  'city-icons/icons/sj-longyearbyen.svg': Icon_city_icons_icons_sj_longyearbyen,
  'city-icons/icons/sk-bratislava.svg': Icon_city_icons_icons_sk_bratislava,
  'city-icons/icons/sm-san-marino.svg': Icon_city_icons_icons_sm_san_marino,
  'city-icons/icons/sn-dakar.svg': Icon_city_icons_icons_sn_dakar,
  'city-icons/icons/st-sao-tome.svg': Icon_city_icons_icons_st_sao_tome,
  'city-icons/icons/sv-san-salvador.svg': Icon_city_icons_icons_sv_san_salvador,
  'city-icons/icons/th-pattaya.svg': Icon_city_icons_icons_th_pattaya,
  'city-icons/icons/tj-dushanbe.svg': Icon_city_icons_icons_tj_dushanbe,
  'city-icons/icons/tl-dili.svg': Icon_city_icons_icons_tl_dili,
  'city-icons/icons/tm-ashgabat.svg': Icon_city_icons_icons_tm_ashgabat,
  'city-icons/icons/tn-tunis.svg': Icon_city_icons_icons_tn_tunis,
  'city-icons/icons/to-nukualofa.svg': Icon_city_icons_icons_to_nukualofa,
  'city-icons/icons/tr-ankara.svg': Icon_city_icons_icons_tr_ankara,
  'city-icons/icons/tr-antalya.svg': Icon_city_icons_icons_tr_antalya,
  'city-icons/icons/tr-istanbul.svg': Icon_city_icons_icons_tr_istanbul,
  'city-icons/icons/tr-izmir.svg': Icon_city_icons_icons_tr_izmir,
  'city-icons/icons/tv-funafuti.svg': Icon_city_icons_icons_tv_funafuti,
  'city-icons/icons/tw-taipei.svg': Icon_city_icons_icons_tw_taipei,
  'city-icons/icons/tz-zanzibar.svg': Icon_city_icons_icons_tz_zanzibar,
  'city-icons/icons/ua-kyiv.svg': Icon_city_icons_icons_ua_kyiv,
  'city-icons/icons/ua-odessa.svg': Icon_city_icons_icons_ua_odessa,
  'city-icons/icons/us-albuquerque.svg': Icon_city_icons_icons_us_albuquerque,
  'city-icons/icons/us-atlanta.svg': Icon_city_icons_icons_us_atlanta,
  'city-icons/icons/us-austin.svg': Icon_city_icons_icons_us_austin,
  'city-icons/icons/us-boston.svg': Icon_city_icons_icons_us_boston,
  'city-icons/icons/us-chicago.svg': Icon_city_icons_icons_us_chicago,
  'city-icons/icons/us-cincinnati.svg': Icon_city_icons_icons_us_cincinnati,
  'city-icons/icons/us-columbus.svg': Icon_city_icons_icons_us_columbus,
  'city-icons/icons/us-denver.svg': Icon_city_icons_icons_us_denver,
  'city-icons/icons/us-hartford.svg': Icon_city_icons_icons_us_hartford,
  'city-icons/icons/us-irvine.svg': Icon_city_icons_icons_us_irvine,
  'city-icons/icons/us-los-angeles.svg': Icon_city_icons_icons_us_los_angeles,
  'city-icons/icons/us-miami.svg': Icon_city_icons_icons_us_miami,
  'city-icons/icons/us-new-orleans.svg': Icon_city_icons_icons_us_new_orleans,
  'city-icons/icons/us-new-york.svg': Icon_city_icons_icons_us_new_york,
  'city-icons/icons/us-peoria.svg': Icon_city_icons_icons_us_peoria,
  'city-icons/icons/us-philadelphia.svg': Icon_city_icons_icons_us_philadelphia,
  'city-icons/icons/us-phoenix.svg': Icon_city_icons_icons_us_phoenix,
  'city-icons/icons/us-pittsburgh.svg': Icon_city_icons_icons_us_pittsburgh,
  'city-icons/icons/us-sacramento.svg': Icon_city_icons_icons_us_sacramento,
  'city-icons/icons/us-san-diego.svg': Icon_city_icons_icons_us_san_diego,
  'city-icons/icons/us-san-francisco.svg': Icon_city_icons_icons_us_san_francisco,
  'city-icons/icons/us-seattle.svg': Icon_city_icons_icons_us_seattle,
  'city-icons/icons/us-st-louis.svg': Icon_city_icons_icons_us_st_louis,
  'city-icons/icons/us-washington.svg': Icon_city_icons_icons_us_washington,
  'city-icons/icons/uy-montevideo.svg': Icon_city_icons_icons_uy_montevideo,
  'city-icons/icons/uz-nukus.svg': Icon_city_icons_icons_uz_nukus,
  'city-icons/icons/uz-tashkent.svg': Icon_city_icons_icons_uz_tashkent,
  'city-icons/icons/va-vatican.svg': Icon_city_icons_icons_va_vatican,
  'city-icons/icons/ve-caracas.svg': Icon_city_icons_icons_ve_caracas,
  'city-icons/icons/vn-da-nang.svg': Icon_city_icons_icons_vn_da_nang,
  'city-icons/icons/vn-hanoi-temple-of-literature.svg': Icon_city_icons_icons_vn_hanoi_temple_of_literature,
  'city-icons/icons/vn-hanoi.svg': Icon_city_icons_icons_vn_hanoi,
  'city-icons/icons/vn-ho-chi-minh.svg': Icon_city_icons_icons_vn_ho_chi_minh,
  'city-icons/icons/vn-vung-tau.svg': Icon_city_icons_icons_vn_vung_tau,
  'city-icons/icons/vu-port-vila.svg': Icon_city_icons_icons_vu_port_vila,
  'city-icons/icons/ws-apia.svg': Icon_city_icons_icons_ws_apia,
  'city-icons/icons/xk-pristina.svg': Icon_city_icons_icons_xk_pristina,
  'city-icons/icons/za-cape-town.svg': Icon_city_icons_icons_za_cape_town,
};
